from enum import StrEnum
from collections.abc import Generator

from _typeshed import Incomplete

from ..utilities import convert_time as convert_time
from ..precision_timer_ext import CPrecisionTimer as CPrecisionTimer

class TimerPrecisions(StrEnum):
    NANOSECOND = "ns"
    MICROSECOND = "us"
    MILLISECOND = "ms"
    SECOND = "s"

class PrecisionTimer:
    _timer: Incomplete
    _laps: list[int]
    def __init__(self, precision: str | TimerPrecisions = ...) -> None: ...
    def __repr__(self) -> str: ...
    @property
    def elapsed(self) -> int: ...
    @property
    def precision(self) -> str: ...
    def reset(self) -> None: ...
    def delay(self, delay: int, *, allow_sleep: bool = False, block: bool = False) -> None: ...
    def set_precision(self, precision: str | TimerPrecisions) -> None: ...
    def format_elapsed(self, *, max_fields: int = 2) -> str: ...
    def lap(self) -> int: ...
    @property
    def laps(self) -> tuple[int, ...]: ...
    def poll(self, interval: int, *, allow_sleep: bool = True, block: bool = False) -> Generator[int, None, None]: ...
