class CPrecisionTimer:
    def __init__(self, precision: str = ...) -> None: ...
    def Delay(self, duration: int, allow_sleep: bool = ..., block: bool = ...) -> None: ...
    def Elapsed(self) -> int: ...
    def Reset(self) -> None: ...
    def SetPrecision(self, precision: str) -> None: ...
    def get_precision(self) -> str: ...
